-- BloomMama — Full Weekly Content Seed (Weeks 1–40)
USE bloommama;

INSERT INTO weekly_content (week, baby_size, baby_weight_g, baby_length_cm, development_en, development_rw, tips_en, tips_rw) VALUES
(4,  'poppy seed cluster', 0, 0.4,
 'Embryo is forming three layers: ectoderm, mesoderm, endoderm.',
 'Uruhinja rufite inzego eshatu zifite akazi kazo.',
 'Take prenatal vitamins daily.',
 'Fata vitamini za gutwita buri munsi.'),

(5,  'orange seed', 0, 0.5,
 'Heart is beating. Brain and spinal cord are forming.',
 'Umutima ukina. Ubwonko n''umurongo w''umugongo birakorwa.',
 'Eat iron-rich foods like beans and spinach.',
 'Rya ibiribwa birimo icyuma nk''ibishyimbo n''imboga.'),

(6,  'sweet pea', 1, 0.6,
 'Facial features begin forming. Tiny hands and feet appear.',
 'Ibiranga mu maso bitangira kugaragara. Intoki n''ibirenge biragaragara.',
 'Stay hydrated. Ginger tea can ease nausea.',
 'Nywa amazi. Icyayi cy''inzabibu birinda isesemi.'),

(7,  'blueberry', 1, 1.0,
 'Brain growing fast. Arm and leg buds appear.',
 'Ubwonko bukura vuba. Amaboko n''amaguru biratangira.',
 'Rest often. Eat small frequent meals.',
 'Pumzika kenshi. Rya gato kenshi.'),

(8,  'kidney bean', 1, 1.6,
 'Fingers forming. Heartbeat visible on ultrasound.',
 'Intoki zirafomoka. Umutima uraboneka kuri ecographie.',
 'Book your first prenatal checkup.',
 'Shyira mu gahunda isuzuma rya mbere.'),

(9,  'grape', 2, 2.3,
 'Muscles forming. Baby can make tiny movements.',
 'Imitsi irafomoka. Uruhinja rurashobora gukora imyambi.',
 'Eat calcium-rich foods: milk, eggs, groundnuts.',
 'Rya ibiribwa birimo calcium: amata, amagi, groundnuts.'),

(10, 'kumquat', 4, 3.1,
 'All vital organs formed. Baby is now called a fetus.',
 'Ingingo zose zifite akazi zafomotse. Uruhinja rurasabwa "fetus."',
 'Light walking is great exercise.',
 'Kugenda gato ni imyitozo myiza.'),

(11, 'fig', 7, 4.1,
 'Baby can hiccup. Fingers and toes fully separated.',
 'Uruhinja rushobora gufata igitutu. Intoki zose zarasiganye.',
 'Avoid salty and processed foods.',
 'Irinda ibiribwa birimo umunyu mwinshi.'),

(12, 'lime', 14, 5.4,
 'Reflexes developing. Fingernails forming.',
 'Imyitwarire itangira. Inzara zirafomoka.',
 'End of first trimester — celebrate your progress!',
 'Iherezo rya trimestre ya mbere — ishime intambwe yawe!'),

(13, 'peach', 23, 7.4,
 'Baby can suck thumb. Eyes moving under eyelids.',
 'Uruhinja rushobora gunywa intoki. Amaso arakora munsi y''ibirenzeri.',
 'Protein is important now: eggs, beans, meat.',
 'Poroteyine ni ngombwa: amagi, ibishyimbo, inyama.'),

(14, 'lemon', 43, 8.7,
 'Baby making facial expressions. Kidneys producing urine.',
 'Uruhinja rugaragariza ibyiyumvo. Impyiko ziroroshya inkari.',
 'Sleep on your left side to improve circulation.',
 'Lala ku ruhande rw''ibumoso kugirango amaraso agerageze neza.'),

(15, 'apple', 70, 10.1,
 'Baby can sense light. Bones getting harder.',
 'Uruhinja rushobora kumva urumuri. Amagufwa arakomera.',
 'Eat vitamin D foods: eggs, fatty fish, fortified milk.',
 'Rya ibiribwa birimo Vitamin D: amagi, isosi, amata yiyongereye.'),

(16, 'avocado', 100, 11.6,
 'Baby pumping blood with stronger heart. Facial muscles active.',
 'Umutima ukomeje gusuka amaraso. Imitsi y''amaso irakora.',
 'Drink at least 8 glasses of water daily.',
 'Nywa amazi nibura glasi 8 buri munsi.'),

(17, 'pear', 140, 13.0,
 'Baby\'s skeleton changing from cartilage to bone.',
 'Amagufwa y\'uruhinja ahindukirira kuva ku cartilage.',
 'Continue prenatal vitamins. Eat sweet potatoes for vitamin A.',
 'Komeza vitamini. Rya ibijumba biryoshe kugirango ubone Vitamin A.'),

(18, 'bell pepper', 190, 14.2,
 'Baby yawning and hiccupping. Ears now in position.',
 'Uruhinja rugaburira no gufata igitutu. Amatwi arari aho akwiye.',
 'Start thinking about your birth plan.',
 'Tangira gutekereza ku gahunda yawe yo kubyara.'),

(19, 'tomato', 240, 15.3,
 'Baby covered in vernix (protective coating). Senses developing.',
 'Uruhinja rwifunze vernix (inkingi). Imyumvire iriteye imbere.',
 'Eat folate-rich foods: beans, lentils, green vegetables.',
 'Rya ibiribwa birimo folate: ibishyimbo, lentils, imboga.'),

(20, 'banana', 300, 16.4,
 'Halfway point! Baby swallowing amniotic fluid. Nails growing.',
 'Hagati y\'inzira! Uruhinja runywa amazi y\'inda. Inzara zikura.',
 'Celebrate week 20! Schedule your anatomy scan.',
 'Ishime ibyumweru 20! Shyira mu gahunda ecographie ya anatomy.'),

(21, 'carrot', 360, 26.7,
 'Baby taste buds forming. Eyebrows and eyelids visible.',
 'Uruhinja rugaragariza integeranyo. Ibihanga n''ibirenzeri biraboneka.',
 'Headaches are common — stay hydrated and rest.',
 'Indwara z''umutwe ni isanzwe — nywa amazi no kupumzika.'),

(22, 'papaya slice', 430, 27.8,
 'Baby\'s lips and eyes more defined. Brainwaves active.',
 'Iminwa n''amaso biraboneka neza. Imishinga y''ubwonko irakora.',
 'Eat zinc-rich foods: pumpkin seeds, beef, chickpeas.',
 'Rya ibiribwa birimo zinc: imbuto za igisubi, inyama, chickpeas.'),

(23, 'large mango', 501, 28.9,
 'Baby can hear your voice clearly. Lungs practicing breathing.',
 'Uruhinja rushobora kumva ijwi ryawe. Ibihaha bigerageza guhumeka.',
 'Talk and sing to your baby — they hear you!',
 'Ganira no kuririmba uruhinja rwawe — rukumva!'),

(24, 'corn cob', 600, 30.0,
 'Baby\'s face fully formed. Fingernails reaching fingertips.',
 'Mu maso y\'uruhinja yose yafomose. Inzara zegereye impera z\'intoki.',
 'Watch for signs of gestational diabetes. Avoid sugary drinks.',
 'Reba ibimenyetso bya diabete y\'inda. Irinda inzoga zirimo isukari.'),

(25, 'cauliflower', 660, 34.6,
 'Baby responding to sounds and light. Fat building up under skin.',
 'Uruhinja gitanga igisubizo ku ijwi n\'urumuri. Amafuta yiyongera munsi y\'uruhu.',
 'Sleep with a pregnancy pillow for comfort.',
 'Lala n\'umwatsi wa gutwita kugirango uhorane amahoro.'),

(26, 'scallion bunch', 760, 35.6,
 'Eyes beginning to open. Brain developing rapidly.',
 'Amaso atangira gufunguka. Ubwonko bukura vuba.',
 'Eat omega-3 foods: fish, walnuts, flaxseed.',
 'Rya ibiribwa birimo omega-3: isosi, walnuts, flaxseed.'),

(27, 'head of cauliflower', 875, 36.6,
 'Baby can distinguish light from dark. Hiccups more frequent.',
 'Uruhinja rushobora gutandukanya urumuri n\'umwijima. Igitutu ciyongera.',
 'Third trimester begins! Increase calcium intake.',
 'Trimestre ya gatatu itangiye! Yongera calcium.'),

(28, 'eggplant', 1005, 37.6,
 'Rapid brain development. Baby blinking and dreaming.',
 'Ubwonko bukura vuba. Uruhinja ruhumira no kora inzozi.',
 'Rest more. Swelling in feet is normal — elevate them.',
 'Pumzika cyane. Kubyimba kw\'ibirenge ni bisanzwe — bishire hejuru.'),

(29, 'butternut squash', 1153, 38.6,
 'Baby\'s muscles and lungs maturing. Bones fully developed.',
 'Imitsi n\'ibihaha by\'uruhinja birakura. Amagufwa yose yafomose.',
 'Attend all prenatal appointments.',
 'Jya ku bikorwa byose bya gutwita.'),

(30, 'large cabbage', 1319, 39.9,
 'Baby storing iron and calcium. Brain growing 3x faster.',
 'Uruhinja rubika icyuma na calcium. Ubwonko bukura inshuro 3 vuba.',
 'Eat iron-rich foods: spinach, beans, red meat.',
 'Rya ibiribwa birimo icyuma: imboga, ibishyimbo, inyama.'),

(31, 'coconut', 1502, 41.1,
 'Baby putting on weight rapidly. Immune system strengthening.',
 'Uruhinja rwiyongera cyane. Ubudahangarwa bukomera.',
 'Eat protein at every meal: eggs, beans, fish.',
 'Rya poroteyine buri gihe: amagi, ibishyimbo, isosi.'),

(32, 'jicama', 1702, 42.4,
 'Toenails and fingernails fully grown. Baby practicing breathing.',
 'Inzara z\'ibirenge n\'intoki zose zakuze. Uruhinja rugerageza guhumeka.',
 'Pack your hospital bag — just in case!',
 'Fata isakoshi y\'ivuriro — ku bwihindure!'),

(33, 'pineapple', 1918, 43.7,
 'Baby\'s bones hardening except skull (for delivery). Gaining weight.',
 'Amagufwa y\'uruhinja arakomera uretse umutwe (kugirango avuke neza).',
 'Practice breathing exercises for labor.',
 'Iga ibikorwa byo guhumeka kugirango ubonabona wo kubyara.'),

(34, 'cantaloupe', 2146, 45.0,
 'Central nervous system maturing. Baby\'s hearing is sharp.',
 'Sisitemu y\'imitsi irakura. Uburyo bwo kumva bw\'uruhinja burakomeye.',
 'Reduce caffeine. Eat small frequent meals.',
 'Gabanya kafeine. Rya gato kenshi.'),

(35, 'honeydew melon', 2383, 46.2,
 'Baby gaining half a pound per week. Kidneys fully developed.',
 'Uruhinja ruyongeraho ibiro buri cyumweru. Impyiko zifite ubushobozi bwuzuye.',
 'Know the signs of labor.',
 'Menya ibimenyetso byo kubyara.'),

(36, 'romaine lettuce head', 2622, 47.4,
 'Baby head-down position (usually). Lungs almost ready.',
 'Uruhinja rwagendereye hepfo (byinshi). Ibihaha birakoroshya.',
 'Rest and prepare your birth space.',
 'Pumzika no gutegura ahantu ho kubyara.'),

(37, 'Swiss chard bunch', 2859, 48.6,
 'Baby considered early term. Practice contractions (Braxton Hicks) common.',
 'Uruhinja rurabona "early term." Ububabare bwo kwigwa (Braxton Hicks) ni isanzwe.',
 'Stay calm. Note contraction timing.',
 'Komera. Andika igihe cy\'ububabare.'),

(38, 'pumpkin', 3083, 49.8,
 'Baby fully developed. Shedding vernix coating. Ready for birth.',
 'Uruhinja rwuzuye. Vernix irapfukama. Rushoboye kuvuka.',
 'Go to the hospital if contractions are 5 min apart.',
 'Jya ku ivuriro niba ububabare bugana iminota 5.'),

(39, 'mini watermelon', 3288, 50.7,
 'Baby adding fat layers. All organs ready. Could arrive any day!',
 'Uruhinja rwongeraho amafuta. Ingingo zose zirakora. Rushobora kuvuka uyu munsi!',
 'Stay near medical care. Keep your phone charged.',
 'Guma hafi y\'ivuriro. Shyira telefoni yawe kuri charge.'),

(40, 'small pumpkin', 3462, 51.2,
 'Full term! Baby is ready. Labor could begin any moment.',
 'Igihe cyuzuye! Uruhinja ruzuye. Kubyara gushobora gutangira igihe icyo aricyo.',
 'You are strong and ready. Trust your body and your care team.',
 'Ufite imbaraga kandi witeguye. Zera umubiri wawe no muganga wawe.');
